name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: macos-13-xl
    steps:
    - uses: actions/checkout@v4
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Run tests
      run: ./run_tests.sh