name: Build

on:
  workflow_dispatch:

jobs:
  build: 
    name: Build and test
    runs-on: macos-13
    steps:
      - name: Checkout repository
      - name: Show current version of Xcode
      - run: xcodebuild -version
      - uses: actions/checkout@v4
      - name: Run tests
      - run:  ./run_tests.sh